version: '3.8'

services:
  tomcat:
    env_file:
      - ./.env
    image: tomcat:latest
    volumes:
      - ../src:/usr/local/tomcat/webapps/ROOT
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        - traefik.http.routers.work-202106__${PROJECT_NAME}.entrypoints=websecure
        - traefik.http.routers.work-202106__${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.demo.hyeon.pro`)
        - traefik.http.routers.work-202106__${PROJECT_NAME}.tls.certresolver=leresolver
        - traefik.http.services.work-202106__${PROJECT_NAME}.loadbalancer.server.port=8080

########################### NETWORKS
networks:
  default:
    external:
      name: DB_work
