name: 🙆‍♂️ 수동 static & build code deploy
on:
  push:
    branches: [develop, main]
    tags:
      - dev/*
    paths:
      - src/**/*
  workflow_dispatch:

jobs:
  source:
    runs-on: ubuntu-latest
    name: 📮 Github 소스코드로 업데이트 `git pull origin develop`
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DEPLOYSERVER_KEY }}
          host: ${{ secrets.DEPLOYSERVER_HOST }}
          username: ${{ secrets.DEPLOYSERVER_USERNAME }}
          port: ${{ secrets.DEPLOYSERVER_PORT }}
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git fetch origin
            git checkout develop
            git branch | grep 'release/*' | xargs git branch -D
            git pull origin develop

  # secrets.SRC = Theme file name
  # secrets.PROJECT_DIR = PROJECT_DIR pwd로 루트부터 지정된 폴더 경로

  build:
    runs-on: ubuntu-latest
    name: 🗳 Theme source build & rsync
    steps:
      - uses: actions/checkout@v2

      - name: 🏗 setup-node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: 🔨 npm install & build
        run: |
          npm install
          npm build

      - name: 📂 Sync files to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOYSERVER_KEY }}
          SERVER_PORT: ${{ secrets.DEPLOYSERVER_RSYNC_PORT }}
          SERVER_IP: ${{ secrets.DEPLOYSERVER_HOST }}
          USERNAME: ${{ secrets.DEPLOYSERVER_USERNAME }}
          FOLDER: "./${{ secrets.SRC }}/dist"
          ARGS: "-rltgoDzvO --ignore-times"
          SERVER_DESTINATION: "${{ secrets.PROJECT_DIR }}/${{ secrets.SRC }}"
